name: CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Test weekly to catch upstream breaking changes
    - cron: '0 0 * * 0'

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        nvim-version: [nightly]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.nvim-version }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ripgrep \
          fd-find \
          python3 \
          python3-pip \
          nodejs \
          npm \
          imagemagick \
          clang \
          build-essential
        
        # Fix fd name on Ubuntu
        mkdir -p ~/.local/bin
        ln -sf $(which fdfind) ~/.local/bin/fd
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Setup config
      run: |
        mkdir -p ~/.config
        ln -s $GITHUB_WORKSPACE ~/.config/nvim
    
    - name: Install plugins
      timeout-minutes: 10
      run: |
        nvim --headless "+Lazy! sync" +qa || true
        nvim --headless "+TSUpdateSync" +qa || true
    
    - name: Run health check
      continue-on-error: true
      run: |
        nvim --headless "+checkhealth" "+w! health.log" +qa || true
        cat health.log || true
    
    - name: Test basic operations
      run: |
        # Test that Neovim starts without errors
        nvim --headless "+lua print('Test successful')" "+qa" 2>&1 | tee startup.log
        
        # Test file operations
        echo "test content" > test.txt
        nvim --headless test.txt "+w" "+qa"
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ matrix.os }}-${{ matrix.nvim-version }}
        path: |
          health.log
          startup.log

  test-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install neovim ripgrep fd node python3 imagemagick llvm
    
    - name: Setup config
      run: |
        mkdir -p ~/.config
        ln -s $GITHUB_WORKSPACE ~/.config/nvim
    
    - name: Install plugins
      timeout-minutes: 10
      run: |
        nvim --headless "+Lazy! sync" +qa || true
    
    - name: Run basic test
      run: |
        nvim --headless "+lua print('Test successful')" "+qa" 2>&1 | tee startup.log

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Lua formatting with stylua
      continue-on-error: true
      uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ github.token }}
        version: latest
        args: --check lua/
